### ISSUE TITLE
Not being able to build the docker image

### ISSUE THREAD

**Issue by alphaO4** [societe-generale/swordphish-awareness#63]
Hello Folks

Im currently trying to setup Swordphish. I first tried to setup swordphish via the documentation provided, but failed (either when uWSGI cant find the router_cache plugin or that the swordphish module cant be found.), so I tried to use the Docker file.

When running docker-compose's build in the docker folder, everything finishes excelt for the `./manage.py generate_Secert_key`, where it spits out
```
#14 1.863   File "/opt/swordphish/Swordphish/__init__.py", line 5, in <module>
#14 1.863     from .celery import app as celery_app
#14 1.863 ModuleNotFoundError: No module named 'Swordphish.celery
```

I have not changed anything in all of the docker files, so I am at a bit of a loss.

If anyone could point me in the right direction, that would be greatly appreciated!

Edit: I am using a Debian 11 image, with nothing installed, other then docker and the "old" not functioning installation of Swordphish.

**Comment by Husseinfo** [comment]
Hello, docker setup is update.
Please make sure to run
```bash
$ docker-compose up --build
```
to rebuild swordphish image.

**Comment by alphaO4** [comment]
Seems to work now. Thanks!
