### ISSUE TITLE
Enhance Wiki documentation

### ISSUE THREAD

**Issue by ghost** [societe-generale/swordphish-awareness#8]
Hello,

I've been struggling for days (yeah, I know, I'm bad :D) to install the swordphish platform because I'm no expert (and don't intend to...) and because sometimes it is not as explicit as it seems (for example python3 in the `$swordphish>mkvirtualenv -p python3 -a /home/swordphish/swordphish/ swordphish` does not work, as python3 is not installed in the /home/ directory but in the /usr/ one). 

Anyway, for ppl who are not experts, it may be a bit trickier than it seems, and that would be a shame not to be able to deploy it, because it really seems to be a nice tool to use.

Thus, would it be possible to enhance a bit the documentation and get a "swordphish-for-dummies" with setp-by-step guide ? Even though it may sound ridicule for you all linux experts, some of us are not :D 

Keep up with the good work (even though yet I have not been able to use your tool), that's a very good addition to the community.

Thanks

**Comment by Heat-Miser** [comment]
Hello,

$swordphish>mkvirtualenv -p python3 

should work if python3 is in your PATH. It doesn't need to be in the current directory to work, but if it's not in your PATH, you can replace it with the full path of the python3 binary,

You can get it by using this command

$> which python3 

Are you sure than python3 is installed on your system ?

**Comment by Sh4dw0lf** [comment]
I guess I have not updated my PATH, explaining my issus :) I succeeded in installing it and it works now, but i could have been simplier :)

Thanks anyway for the contrbution, it really is nice !

**Comment by Heat-Miser** [comment]
Great news. Can I close this issue then ?

**Comment by Sh4dw0lf** [comment]
If you don't think it may be necessary to enhance the current documentation be my guest :) 

Have a good day,
