### ISSUE TITLE
server sizing

### ISSUE THREAD

**Issue by greenmouse147** [societe-generale/swordphish-awareness#9]
Hello, 
first, thank you for this work. 

I would like to know what sizing you recommend for the Swordphish server

in the documentation, you specify that 100k mail is a big campaign,
what does it take to support the load of a big campaign? 

thank you

Axel

**Comment by Heat-Miser** [comment]
Hello,

Our instance run on this kind of server

CPU :  Intel  Xeon E3-1270v6 - 4c/8t - 3,8GHz /4,2GHz
RAM :  64Go DDR4 ECC 2400 MHz

The most consuming actions are big target list loads.
